name: Bug Report
description: File a bug report
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report for [Enterr](https://github.com/JonBunator/Enterr). Note: this template is only for bug reports. Please use [Github Discussions](https://github.com/JonBunator/Enterr/discussions) for any questions.
  - type: checkboxes
    id: preconditions
    attributes:
      label: Things to check
      options:
        - label: I have searched the **existing issues** for this bug
          required: true      
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Please describe the issue briefly. You can use code-snippets, screenshots, or videos to further explain your problem.
      placeholder: Describe your issue!
    validations:
      required: true
  - type: textarea
    id: repro-steps
    attributes:
      label: Reproduction steps
      description: How do you trigger this bug? Please walk us through it step by step.
      value: |
        1.
        2.
        3.
        ...
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted.
      render: shell
  - type: input
    id: bug-version
    attributes:
      label: Version (bug)
      description: With which version are you experiencing the issue?
      placeholder: v2.x.x
    validations:
      required: true
  - type: input
    id: working-version
    attributes:
      label: Version (working)
      description: Did it work on a previous version? If so, which version?
      placeholder: v2.x.x
  - type: dropdown
    id: os
    attributes:
      label: On which host systems are you experiencing the issue?
      description: You don't have to test it on every system.
      multiple: true
      options:
        - Windows
        - macOS
        - Linux
        - Synology NAS
        - Other
    validations:
      required: true
  - type: checkboxes
    id: pr
    attributes:
      label: Pull Request
      description: If you need this fixed soon, consider submitting a Pull Request! I greatly appreciate all contributions and will review them as soon as possible!
      options:
        - label: I would like to do a Pull Request
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/JonBunator/Enterr/blob/main/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
